services:
  - type: worker
    name: football-twitter-bot
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: TWITTER_POST_USERNAME
        sync: false
      - key: TWITTER_POST_PASSWORD
        sync: false
      - key: TWITTER_POST_EMAIL
        sync: false
      - key: TWITTER_POSTING_MODE
        value: real